name: Publish
on:
  release:
    types: [ published ]
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Set up java
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Publish artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bazel run --stamp --define "maven_repo=https://maven.pkg.github.com/cyberdelia/starlark" --define "maven_user=cyberdelia" --define "maven_password=${GITHUB_TOKEN}" //:starlark.publish

